End nether metals
Soartex-Modded/Modded-1.10.x pull request #25
Opened 2016-12-22 11:05 UTC by Biggbosscurser

Besides couple of texture missing End metals and Nether metals mods are done.

2016-12-22 21:25 UTC, zISKo666 reviewed
Well, I miss the cracks and shadows. See my examples, please.

![nether_diamond_ore](https://cloud.githubusercontent.com/assets/6992216/21440934/d4e14e32-c895-11e6-90bb-c80957e096b0.png)
![end_diamond_ore](https://cloud.githubusercontent.com/assets/6992216/21440885/86337a9e-c895-11e6-8413-7df124432dd5.png)

2016-12-22 21:35 UTC, Biggbosscurser commented
Yes, i got some comments and suggestions on how to do the shadows and cracks. This request can be marked as awaiting for changes. I will fix the textures when i can do the time.

2016-12-22 22:22 UTC, alfw requested changes
The ``mod.json`` file format is importen for our scripts to run right. Those changes needed to be made.

2016-12-22 22:22 UTC, alfw commented on End_Metals/mod.json
> +  "mod_dir": "/end_metals/",
This  need to match the folder name itself. ``"mod_dir": "/End_Metals/"``

2016-12-22 22:22 UTC, alfw commented on Nether_Metals/mod.json
> +  "mod_dir": "/nether_metals/",
This need to match the folder name itself. "mod_dir": "/Nether_Metals/"

2016-12-23 12:06 UTC, mgdgfbhevdyeh commented on End_Metals/mod.json
> +  "mod_dir": "/end_metals/",
@Biggbosscurser change,please.

2017-01-16 07:21 UTC, alfw commented
Still waiting for those changes @Biggbosscurser !

2017-01-16 14:08 UTC, Biggbosscurser commented
I am so sorry guys I've been crazy busy lately and totally forgot about these.I will get back to it and hopefully done them before midnight.

2017-01-18 20:40 UTC, alfw commented on Nether_Metals/mod.json
> +  "mod_dir": "/Nether_metals/",
Hey, this need to be `Nether_Metals`.

2017-02-20 12:34 UTC, alfw approved these changes

2017-02-20 12:36 UTC, merged