XNet machine textures & Better Foliage short grass & two smail mod
Soartex-Modded/Modded-1.10.x pull request #44
Opened 2017-04-23 11:48 UTC by mgdgfbhevdyeh

XNet many Templates form RFTOOLS texture

2017-04-23 13:15 UTC, alfw requested changes
Hello,
Those changes is needed to make our scripts happy. This should not be merged until fixed.

2017-04-23 13:15 UTC, alfw commented on Better_Foliage/mod.json
> +  "mod_dir": "/BetterFoliage/",
Hello,
The ``mod_dir`` need to match the dir where the texutres are stored. In this it has to be ``"mod_dir": "/Better_Foliage/",``

2017-04-23 13:15 UTC, alfw commented on Flour_Power/mod.json
>    "mod_dir": "/FlourPower/",
Hello,
The ``mod_dir`` need to match the dir where the texutres are stored. In this it has to be "mod_dir": "/Flour_Power/",

2017-04-24 04:51 UTC, mgdgfbhevdyeh commented
OK I know :-D
sorry my is bad for write mod.json

2017-04-24 17:55 UTC, alfw approved these changes

2017-05-07 03:52 UTC, merged